### ISSUE TITLE
gxi has been renamed to "Tau"

### ISSUE THREAD

**Issue by Cogitri** [flathub/com.github.Cogitri.gxi#1]
Hey there,

not quite sure what the procedure on this is, but gxi has been renamed to Tau and is now hosted on GNOME infra, as such the app-id changed to "org.gnome.Tau".

CC @barthalion @nedrichards

**Comment by barthalion** [comment]
We can mark this app as EOL with message telling user where to switch, but you will need to create new pull request for new repository. Flatpak doesn't really support renames.

**Comment by Cogitri** [comment]
Alright, thanks for the info. Renaming things is indeed a bit annoying - but that's to be expected. I'll file a new PR in a bit, thank you
